apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-image
spec:
  steps:
    - computeResources: {}
      image: 'registry.access.redhat.com/ubi9:latest'
      name: clone
      script: |
        yum install buildah -y
        buildah --storage-driver vfs build -f /workspace/build/Dockerfile -t image-registry.openshift-image-registry.svc:5000/pfan/hello-shfe:v1 /workspace/source/code
        buildah --storage-driver vfs push image-registry.openshift-image-registry.svc:5000/pfan/hello-shfe:v1
      securityContext:
        capabilities:
          add:
            - SETFCAP
  workspaces:
    - description: source code folder
      name: source
    - description: dockerfile
      name: build
